# MySQL. Versions 5.5.8 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: <%= ENV['PROD_MYSQL_DATABASE'] %>
  username: <%= ENV['PROD_MYSQL_USER'] %>
  password: <%= ENV['PROD_MYSQL_PASSWORD'] %>
  host: <%= ENV['PROD_MYSQL_HOST'] %>
